### ISSUE TITLE
UnboundLocalError: local variable 'line_idx' referenced before assignment

### ISSUE THREAD

**Issue by lmh0921** [stanford-futuredata/ColBERT#78] opened 2021-11-22 15:16 UTC
Hello,

I am using your code for training.
I generate a dataset triplet according to your format.
It can run a little period, however, after somewhile, it shows:

[Nov 22, 16:02:45] Traceback (most recent call last):
  File "IR/code/colbert/colbert/utils/runs.py", line 70, in context
    yield
  File "IR/code/colbert/colbert/train.py", line 30, in main
    train(args)
  File "IR/code/colbert/colbert/training/training.py", line 91, in train
    for batch_idx, BatchSteps in zip(range(start_batch_idx, args.maxsteps), reader):
  File "IR/code/colbert/colbert/training/eager_batcher.py", line 42, in __next__
    self.position += line_idx + 1
UnboundLocalError: local variable 'line_idx' referenced before assignment

Do you know what is the problem?
Besides, self.position += line_idx + 1, the line_idx is a local variable, would there the issue,
and could you explain the usage of self.position?

Thanks a lot!

**Comment by okhat** [comment] 2021-11-22 23:46
Ah, this looks like an edge case in the EagerBatcher. Basically, you ran out of training examples and the total number of examples was divisible by the batch size.

Adding line_idx = 0 at Line 32 (in eager_batcher.py) would fix this for now. Let me know if you face any other issues.

**Comment by lmh0921** [comment] 2021-11-24 00:12
Thanks a lot for fast reply.
Actually the problem happened after my triplet file is finished reading, the same as https://github.com/stanford-futuredata/ColBERT/issues/49

Adding line_idx = 0 would remove the Traceback, but actually, this is when finishing training😂

Overall, thanks

**Comment by okhat** [comment] 2021-11-24 00:22
Yeah, but line_idx = 0 should still be correct.

Feel free to post more questions here, or to close it if the issue is now resolved.

**Comment by okhat** [comment] 2021-11-26 22:11
Closing. Feel free to re-open if you have more questions!

**Closed by okhat** 2021-11-26 22:11 UTC
