### ISSUE TITLE
Can the index be updated (e.g. after a single document change)?

### ISSUE THREAD

**Issue by lalenzos** [stanford-futuredata/ColBERT#111] opened 2022-06-13 13:46 UTC
Hello,
I wanted to ask if it is possible to update the index, e.g. after a single document has changed in content, because updating the entire index every time is relatively time- and ressource-consuming.
Is there a way to do that or any other hint?

**Comment by santhnm2** [comment] 2022-06-17 22:20
Hi @lalenzos, this is feature we are planning to add soon - stay tuned!

**Comment by mq55** [comment] 2022-06-30 07:13
Can you share the reproduction of this code, my email is 774747234@qq.com, can you add a contact information?

**Comment by okhat** [comment] 2023-01-31 03:17
Merged this feature recently. Closing

**Closed by okhat** 2023-01-31 03:17 UTC

**Comment by ishaan16** [comment] 2023-05-06 21:55
So how to use this feature?  What I want to do is regularly update the .tsv with newer documents. I tried to use `indexer.index(..., overwrite="resume")` but that did not update the latest documents in the index. Did I miss something (I would not have asked if there had been any PR linked to this issue)? Thanks in advance

**Comment by sarisel** [comment] 2023-05-07 22:03
https://github.com/stanford-futuredata/ColBERT/blob/main/colbert/index_updater.py

**Comment by jon-chuang** [comment] 2023-07-10 02:23
Hello, could I simply add documents to an empty index in a batched, continous fashion? Will this screw up the centroids somehow? To my understanding, Faiss supports this, but the compression method may not, is this correct?

**Comment by jon-chuang** [comment] 2023-07-10 02:42
Another question I have is whether, after a number of updates, one can retrain the compression and reindex the centroids. Perhaps this is equivalent to rebuilding from scratch?

**Comment by okhat** [comment] 2023-07-10 07:23
You can’t (or definitely shouldn’t, at least) start with a tiny or empty index and add stuff. The initial index must be large and representative, because it determines the centroids. 

If it’s really small, please use nbits=8 (or nbits=4) to reduce the dependence on centroids.

Retraining centroids would be by rebuilding the index indeed. This is actually conceptually necessary since the compression is inherently lossy.
